version: '3'

# Prometheus
# ----------------------------------------------------------------
# Docs at https://prometheus.io/
#
# note: run from ../Taskfile.yaml

tasks:  
  deps: 
    cmds:
      - brew install helm

  install:
    dir: ../
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm install -f deployments/kubernetes/prometheus/values.yaml prometheus-community/prometheus --generate-name

  values:
    cmds: 
      - helm show values prometheus-community/prometheus

  remove:
    cmds:
      - helm uninstall prometheus-community/prometheus
  
  open:
    cmds: 
      # - open http://localhost:9090
      - kubectl --namespace default port-forward {{.POD_NAME}} 9090
    vars:
      POD_NAME:
        sh: kubectl get pods --namespace default -l "app=prometheus,component=server" -o jsonpath="{.items[0].metadata.name}"

  alert-manager:
    cmds: 
      - open http://localhost:9093
      - kubectl --namespace default port-forward {{.POD_NAME}} 9093
    vars:
      POD_NAME: 
        sh: kubectl get pods --namespace default -l "app=prometheus,component=alertmanager" -o jsonpath="{.items[0].metadata.name}"
  
  push-gateway-open:
    cmds: 
      - kubectl --namespace default port-forward {{.POD_NAME}} 9091
    vars:
      POD_NAME: 
        sh: kubectl get pods --namespace default -l "app=prometheus,component=pushgateway" -o jsonpath="{.items[0].metadata.name}"

  push-metrics:
    cmds: 
      - sleep 5
      - |
        for (( i=1; ;i++))
        do
          curl -s -o ../tmp/metrics.yaml http://localhost:8080/metrics
          curl -s --data-binary @../tmp/metrics.yaml http://localhost:9091/metrics/job/hello_api
          echo $i
          sleep 10
        done

  push-metrics-remove:
    cmds:
      - curl -X DELETE http://localhost:9091/metrics/job/hello_api