version: '3'

# note: run from ../Taskfile.yaml

tasks:
  
  swag-deps:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
    
  swag-init:
    dir: ../
    cmds:
      - swag init -o api -g cmd/hello.go

  swag-open:
    cmds:
      - open http://localhost:8080/api/v1/docs/index.html#/