version: '3'

# Swagger
# ----------------------------------------------------------------
# Docs at https://github.com/swaggo/swag
#
# note: run from ../Taskfile.yaml

tasks:
  init:
    cmds:
      - swag init -o api -g cmd/{{.COMMAND}}.go
    vars:
      COMMAND:
        sh: echo $COMMAND

  open:
    cmds:
      - open http://{{.HOSTNAME}}:{{.PORT}}/api/v1/docs/index.html#/
    vars:
      HOSTNAME:
        sh: echo $HOSTNAME
      PORT:
        sh: echo $PORT