version: '3'

# Swagger
# ----------------------------------------------------------------
# Docs at https://github.com/swaggo/swag
#
# note: run from ../Taskfile.yaml

tasks:
  deps:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
    
  init:
    dir: ../
    cmds:
      - swag init -o api -g cmd/hello.go

  open:
    cmds:
      - open http://localhost:8080/api/v1/docs/index.html#/