root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  args_bin = []
  # bin = ""
  cmd = "cd envs/go && task go:rebuild"
  delay = 10000
  exclude_dir = ["build", ".github", ".vscode", "tools", "dist"]
  exclude_file = [".gitignore", ".dockerignore", ".golangci.yml", "go.mod", "go.sum", "README.md"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = true
  full_bin = "cd envs/go && task go:run"
  include_dir = ["cmd", ".", "internal"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "1s"
  # log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
