changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
# changeFormat: '* {{.Body}}'
changeFormat: >-
  * [#{{.Custom.Issue}}](https://github.com/gsantoro/go-sample-app/issues/{{.Custom.Issue}}) {{.Body}}
headerFormat: |
  Updates:
  {{- range $kind := (kinds .Changes | uniq)}}
    {{- $changeCount := (kinds $.Changes | count $kind)}}
    {{- if gt $changeCount 0 }}
    * {{$kind}}: {{$changeCount}}
    {{- end}}
  {{- end}}
kinds:
- label: Added
- label: Changed
- label: Deprecated
- label: Removed
- label: Fixed
- label: Security
newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 1
custom:
- key: Issue
  type: int
  minInt: 1
