version: '3'

### IMPORTANT NOTE: only import via inline definition. 
# do NOT use the following definition otherwise you won't be able to overwrite global variables
#
includes:
  # NOTE: How to use it. 
  # All the taskfiles under `tools/taskfiles/lib` are automatically downloaded from the `gsantoro/automation` repo
  # thanks to the taskfile `automation`. If those taskfiles are not there yet, follow these steps
  # 1. Comment out all the taskfiles with paths that start with `tools/taskfiles/lib`
  # 2. Run `task automation`
  # 3. Uncomment all the taskfiles with paths that start with `tools/taskfiles/lib`
  #
  # For this to work you need to have a .env.private with `GITHUB_TOKEN`.
  # This file is not under git since it contain secrets
  docker: tools/taskfiles/lib/docker.taskfile.yml
  go: tools/taskfiles/lib/go.taskfile.yml
  devenv: tools/taskfiles/lib/devenv.taskfile.yml
  direnv: tools/taskfiles/lib/direnv.taskfile.yml
  skaffold: tools/taskfiles/lib/skaffold.taskfile.yml
  trivy: tools/taskfiles/lib/trivy.taskfile.yml
  helm: tools/taskfiles/lib/helm.taskfile.yml
  prometheus: tools/taskfiles/lib/prometheus.taskfile.yml
  grafana: tools/taskfiles/lib/grafana.taskfile.yml
  k3d: tools/taskfiles/lib/k3d.taskfile.yml
  ckd8s: tools/taskfiles/lib/cdk8s.taskfile.yml

  automation: tools/taskfiles/automation.taskfile.yml
  main: tools/taskfiles/main.taskfile.yml
  
  
