version: '3'

vars:
  WORKSPACE: "~/workspace/personal"
  KUBERNETES_VERSION: v1.24.0
  

### IMPORTANT NOTE: only import via inline definition. 
# do NOT use the following definition otherwise you won't be able to overwrite global variables
#
includes:
  changie: tools/taskfiles/lib/changie.taskfile.yml
  docker: tools/taskfiles/lib/docker.taskfile.yml
  swagger: tools/taskfiles/lib/swagger.taskfile.yml
  go: tools/taskfiles/lib/go.taskfile.yml
  releaser: tools/taskfiles/lib/releaser.taskfile.yml
  devenv: tools/taskfiles/lib/devenv.taskfile.yml
  chainguard: tools/taskfiles/lib/chainguard.taskfile.yml
  ghcr: tools/taskfiles/lib/ghcr.taskfile.yml
  wolfi: tools/taskfiles/lib/wolfi.taskfile.yml
  kind: tools/taskfiles/lib/kind.taskfile.yml  
  skaffold: tools/taskfiles/lib/skaffold.taskfile.yml

  env: tools/taskfiles/lib/env.taskfile.yml  # if not already in lib, download manually. used by `tasks`
  gh: tools/taskfiles/lib/gh.taskfile.yml  # if not already in lib, download manually. used by `tasks`
  
  tasks: tools/taskfiles/tasks.taskfile.yml
  
  
  

tasks:
  deps:
    cmds:
      - brew install go-task/tap/go-task
      - task: devenv:deps
      - task: gvm:deps