version: '3'

dotenv: ['.env']

vars:
  WORKSPACE: "~/workspace/personal"
  KUBERNETES_VERSION: v1.24.0
  

### IMPORTANT NOTE: only import via inline definition. 
# do NOT use the following definition otherwise you won't be able to overwrite global variables
#
includes:
  asciinema: tools/taskfiles/asciinema.taskfile.yaml
  changie: tools/taskfiles/changie.taskfile.yaml
  # docker: tools/taskfiles/docker.taskfile.yaml
  swagger: tools/taskfiles/swagger.taskfile.yaml
  go: tools/taskfiles/go.taskfile.yaml
  grafana: tools/taskfiles/grafana.taskfile.yaml
  gvm: tools/taskfiles/gvm.taskfile.yaml
  k8s: tools/taskfiles/k8s.taskfile.yaml
  pre-commit: tools/taskfiles/pre-commit.taskfile.yaml
  prometheus: tools/taskfiles/prometheus.taskfile.yaml
  releaser: tools/taskfiles/releaser.taskfile.yaml
  test: tools/taskfiles/test.taskfile.yaml
  devenv: tools/taskfiles/devenv.taskfile.yaml
  env: tools/taskfiles/env.taskfile.yaml
  

tasks:
  deps:
    cmds:
      - brew install go-task/tap/go-task
      - task: devenv:deps
      - task: gvm:deps
      # - task: asciinema:deps
      # - task: docker:deps
      # - task: grafana:deps
      # - task: pre-commit:deps
      # - task: prometheus:deps
      # - task: releaser:deps

  default:
    - task: env