version: '3'

# dotenv: ['.env']

vars:
  WORKSPACE: "~/workspace/personal"
  KUBERNETES_VERSION: v1.24.0
  

### IMPORTANT NOTE: only import via inline definition. 
# do NOT use the following definition otherwise you won't be able to overwrite global variables
#
includes:
  changie: tools/taskfiles/lib/changie.taskfile.yml
  docker: tools/taskfiles/lib/docker.taskfile.yml
  swagger: tools/taskfiles/lib/swagger.taskfile.yml
  go: tools/taskfiles/lib/go.taskfile.yml
  releaser: tools/taskfiles/lib/releaser.taskfile.yml
  devenv: tools/taskfiles/lib/devenv.taskfile.yml
  
  env: tools/taskfiles/env.taskfile.yml
  tasks: tools/taskfiles/tasks.taskfile.yml
  

tasks:
  deps:
    cmds:
      - brew install go-task/tap/go-task
      - task: devenv:deps
      - task: gvm:deps
      # - task: asciinema:deps
      # - task: docker:deps
      # - task: grafana:deps
      # - task: pre-commit:deps
      # - task: prometheus:deps
      # - task: releaser:deps

  default:
    - task: env