version: '3'

tasks:
  build:
    cmds:
      - go build -v -i main.go

  run:  
    cmds: 
      - air -c .air.toml

  install-linter:
    cmds: 
    # version: 1.48.0_1
      - brew install golangci-lint
      - brew upgrade golangci-lint