version: '3'

### IMPORTANT NOTE: only import via inline definition. 
# do NOT use the following definition otherwise you won't be able to overwrite global variables
#
includes:
  docker: tools/taskfiles/lib/docker.taskfile.yml
  go: tools/taskfiles/lib/go.taskfile.yml
  devenv: tools/taskfiles/lib/devenv.taskfile.yml
  direnv: tools/taskfiles/lib/direnv.taskfile.yml
  chainguard: tools/taskfiles/lib/chainguard.taskfile.yml
  k8s-kind: tools/taskfiles/lib/k8s.kind.taskfile.yml  
  skaffold: tools/taskfiles/lib/skaffold.taskfile.yml
  trivy: tools/taskfiles/lib/trivy.taskfile.yml
  helm: tools/taskfiles/lib/helm.taskfile.yml
  prometheus: tools/taskfiles/lib/prometheus.taskfile.yml
  grafana: tools/taskfiles/lib/grafana.taskfile.yml

  gh: tools/taskfiles/gh.taskfile.yml  # if not already in lib, download manually. used by `tasks`
  
  tasks: tools/taskfiles/tasks.taskfile.yml
  
  
  

tasks:
  deps:
    desc: Install dependencies
    cmds:
      - brew install go-task/tap/go-task