version: '3'

dotenv: ['../.env']

vars:
  WORKSPACE: "~/workspace/personal"
  KUBERNETES_VERSION: v1.24.0

includes:
  asciinema: taskfiles/asciinema.taskfile.yaml
  changie: taskfiles/changie.taskfile.yaml
  docker: taskfiles/docker.taskfile.yaml
  swagger: taskfiles/swagger.taskfile.yaml
  go: taskfiles/go.taskfile.yaml
  grafana: taskfiles/grafana.taskfile.yaml
  gvm: taskfiles/gvm.taskfile.yaml
  k8s: taskfiles/k8s.taskfile.yaml
  pre-commit: taskfiles/pre-commit.taskfile.yaml
  prometheus: taskfiles/prometheus.taskfile.yaml
  releaser: taskfiles/releaser.taskfile.yaml
  test: taskfiles/test.taskfile.yaml
  

tasks:
  deps:
    cmds:
      - brew install go-task/tap/go-task
      - task: asciinema:deps
      - task: changie:deps
      - task: docker:deps
      - task: go:deps
      - task: grafana:deps
      - task: gvm:deps
      - task: k8s:deps
      - task: pre-commit:deps
      - task: prometheus:deps
      - task: releaser:deps