basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: Giuseppe Santoro
  description: Sample application in Go
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Go Sample App
  version: "1.0"
paths:
  /health:
    get:
      description: Responds with status=ok.
      produces:
      - application/json
      responses: {}
      summary: Health
      tags:
      - Health
  /ping:
    get:
      description: Responds with Pong.
      produces:
      - application/json
      responses: {}
      summary: Ping
      tags:
      - ping
swagger: "2.0"
